### ISSUE TITLE
browser access error

### ISSUE THREAD

**Issue by lihong12500** [hexya-erp/hexya#126]
1.when access the server at http://172.16.16.17:8080, browser having error...information

SyntaxError: expected expression, got '<'

http://172.16.16.17:8080/web/webclient/locale/en_US:4
Traceback:

2、using login and password loging web ,will having information
 Traceback:
TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at computeFloatOuterWidthWithMargins (http://172.16.16.17:8080/static/web/src/js/core/dom.js:551:27)
    at _adapt (http://172.16.16.17:8080/static/web/src/js/core/dom.js:540:35)
    at Object.initAutoMoreMenu (http://172.16.16.17:8080/static/web/src/js/core/dom.js:474:9)
    at http://172.16.16.17:8080/static/web/src/js/chrome/menu.js:72:17
    at async Promise.all (index 2)
    at async Promise.all (index 0)

**Comment by npiganeau** [comment]
Make sure you have installed dart-sass (https://github.com/sass/dart-sass/releases) before running the server.
